name: open pr

on:
  push:
    branches:
      - deploy/prd

jobs:
  open_pr:
    name: open pr by pushing to deploy/prd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
      - name: Set git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/package-lock.json
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-v1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Create PR
          title: 'chore(release): publish'
          body: 'This is an auto-generated PR.'
          base: 'main'
